### ISSUE TITLE
Can't connect to SNI-only server

### ISSUE THREAD

**Issue by moviuro** [nvllsvm/Audinaut#38] opened 2018-07-28 08:29 UTC
Hi,

I have a server at https://anthro.popho.be (it's available and working in any browser), but Audinaut can't reach it. See [SSLLabs report](https://www.ssllabs.com/ssltest/analyze.html?d=anthro.popho.be&hideResults=on&latest).

Audinaut reports: "*Connection failure. A problem occured communicating with the server. Please check the server address and verify that you can connect using a regular browser on your device.*". So I did, and we're here.

I can create an account for you to test on my server.

**Comment by nvllsvm** [comment] 2018-07-28 23:39
Email me an username+password to ar@nullsum.net and I'll be happy to investigate.

**Comment by nvllsvm** [comment] 2018-07-29 19:56
Ampache implements version 1.11.0 of the Subsonic API - supporting the legacy authentication method. Audinaut uses only the method introduced in 1.13.0.

Closing as duplicate of https://github.com/ampache/ampache/issues/1405

**Closed by nvllsvm** 2018-07-29 19:56 UTC
